In [1]:
from env import *

In [4]:
numba_main_2(random_player,1000,0,0)

(195, 0)

In [ ]:
!python env_print.py

In [2]:
# @njit()
def p_ran(state, perData):
    validActions = getValidActions(state)
    arr_action = np.where(validActions==1)[0]
    idx = np.random.randint(0, arr_action.shape[0])
    print(state[82:86])
    return arr_action[idx], perData

In [11]:
numba_main_2(p_ran,1,0,0)

[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 1. 1. 1.]
[1. 0. 1. 1.]
[1. 0. 1. 1.]
[1. 0. 1. 1.]
[1. 0. 0. 0.]
[0. 0. 0. 0.]


(1, 0)